# app/main.py
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware  # <--- add this
from sqlalchemy import text
from app.deps import crud
from app.config import settings
from app.routers import auth, users, chat, files, admin

app = FastAPI(
    title=settings.APP_NAME,
    debug=settings.DEBUG
)

# -----------------------------
# CORS configuration
# -----------------------------
origins = [
    "http://localhost:5173",               # your local frontend for dev
    "https://your-frontend.onrender.com"   # your deployed frontend
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,      # allows requests from these URLs
    allow_credentials=True,     # if sending cookies / auth headers
    allow_methods=["*"],        # allow all HTTP methods
    allow_headers=["*"],        # allow all headers
)

# -----------------------------
# Database bootstrap (PostgreSQL SAFE)
# -----------------------------
@app.on_event("startup")
def startup_event():
    with crud.engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS documents (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                content TEXT NOT NULL
            )
        """))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                email TEXT UNIQUE NOT NULL
            )
        """))

# -----------------------------
# Routers
# -----------------------------
app.include_router(auth.router, prefix="/auth", tags=["Auth"])
app.include_router(users.router, prefix="/users", tags=["Users"])
app.include_router(chat.router, prefix="/chat", tags=["Chat"])
app.include_router(files.router, prefix="/files", tags=["Files"])
app.include_router(admin.router, prefix="/admin", tags=["Admin"])

# -----------------------------
# Health check
# -----------------------------
@app.get("/health")
def health_check():
    return {
        "status": "ok",
        "app": settings.APP_NAME
    }